### ISSUE TITLE
Would a plugin update be possible for the last Phile version?

### ISSUE THREAD

**Issue by ghost** [PhileCMS/phileRSSFeed#1]
Hello Developers,

unfortunately this plugin is not compatible with the latest Phile CMS version.

Would it be hard to make an update of the plugin? I would like to use it and currently the Phile CMS has also developed further.

Thanks in advance.

P.S. under `/feed` is an Error 404 page when I want to call it in the browser.

**Comment by Schlaefer** [comment]
Done.
