### ISSUE TITLE
Absolute Links in Content

### ISSUE THREAD

**Issue by WestonHanners-Earnin** [PhileCMS/phileRSSFeed#2]
Is it possible to force links to render as absolute links instead of relative links in the feed?

**Comment by Schlaefer** [comment]
You could achieve that in different ways. Without testing and just looking at the code a quick solution should be:

```php
$router = Container::getInstance()->get('Phile_Router'); // add e.g. at [1]
...
'url' => $router->urlForPage($page->getPageId(), true), // replace at [2]
```

[1] https://github.com/PhileCMS/phileRSSFeed/blob/master/Classes/Plugin.php#L48
[2] https://github.com/PhileCMS/phileRSSFeed/blob/master/Classes/Plugin.php#L57

**Comment by WestonHanners-Earnin** [comment]
I had figured this one out, what I meant was the links in content. I was trying to validate my feed with https://validator.w3.org/feed/ and I get a complaint about relative links in the content.

**Comment by Schlaefer** [comment]
I misunderstood that. Makes sense, good question. Practically all of my PhileCMS knowledge is swapped out of my brain at the moment, so I don't have a good/authoritative answer.

Essentially it comes down to encourage the (3rd party) markup-parser to create HTML content with absolute links. In that case the RSS plugin will also automatically emit it. Is that possible (with MarkdownExtra), don't know from the top of my head.

[1] uses a simple regex to rewrite every media content URL at [2], maybe that's an option? Rewrite every relative looking URL and inject the absolute webroot? Not nice, but a hack which could work. (Or maybe in before parse content, if that's easier. Or maybe even as a middleware.)

[1] https://github.com/Schlaefer/phileServeContentFiles
[2] https://github.com/Schlaefer/phileServeContentFiles/blob/master/Classes/Plugin.php#L59

**Comment by WestonHanners-Earnin** [comment]
I updated Page.php:134 in the model with

`$content = preg_replace('~(?:src|action|href)=[\'"]\K[^\'"]*~',"$baseUrl/$0",$content);`

and this seems to do the trick.

**Comment by Schlaefer** [comment]
Nice. :+1: 

Maybe we should update the atom template and also include the `xml:base` attribute as mentioned here: https://github.com/jekyll/jekyll-feed/issues/185#issuecomment-319683646

I assume that the w3.org validator is still going to mark it as a problem, as absolute paths are the only way to be sure, but it should improve the situation out of the box on any decent xml/atom parser. - If that solution is good enough for jekyll it should be good enough for Phile. :wink:

**Comment by WestonHanners-Earnin** [comment]
Fixed as good as it can be for now.
